# Generated by Django 4.1.2 on 2022-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
